### ISSUE TITLE
Google Drive folder for trained Model is empty

### ISSUE THREAD

**Issue by jaste111** [Anushka-Prakash/RumourEval-2019-Stance-Detection#1]
@Anushka-Prakash 

Hi, 
I tried to download the trained model from Google Drive. 

Unfortunately,  the Google Drive Folder is empty.

Best regards.

**Comment by H-TayyarMadabushi** [comment]
Hi, 

Could you let us know which link you are describing? The save paths are for your convenience when training the models.

**Comment by jaste111** [comment]
Hi,

thank you for your quick response.

I'm talking about the link you mentioned in the README https://github.com/Anushka-Prakash/RumourEval-2019-Stance-Detection#trained-models

**Comment by H-TayyarMadabushi** [comment]
Yes, I'm afraid we don't store copies of this. We stopped storing them because of incompatibilities with more recent PyTorch models. I'll update the readme. If you do train the models again, and would like them included on here, do let me know and I'll link to your trained models with a note saying you contributed them.
